name: fluxdataqaqc
channels:
  - conda-forge
  - defaults
dependencies:
  - bokeh>=2.0
  - pandas>=1.0
  - python>=3.7
  - refet
  - scikit-learn
  - netCDF4
  - xlrd>=1.2.0
  - numpy>=1.15
  - xarray
  - openpyxl
